### ISSUE TITLE
dynamic icons?

### ISSUE THREAD

**Issue by delaneyj** [antfu/unplugin-icons#10]
Say you have `const providers = ref(['google','facebook'])` and what to load icons based on the names.  How could you do that with this library?  For static icons its working great!

**Comment by antfu** [comment]
#5 #7 #8 #9

Again, I am happy to receive any ideas about implementing the dynamics icons.

**Comment by rimday** [comment]
use purge icons https://github.com/antfu/purge-icons

**Comment by lucien-efx** [comment]
Hi @antfu, since purge-icons is no longer maintained, as per your comment on purge-icons [issue #24](https://github.com/antfu/purge-icons/issues/24#issuecomment-956451403), is it possible to merge some of purge-icons features into unplugin-icons?
