### ISSUE TITLE
svelte compiler add extra '>'

### ISSUE THREAD

**Issue by RyanYANG52** [antfu/unplugin-icons#106]
Awesome lib! one small thing I notice:
In `SvelteCompiler` 
```
const openTagEnd = svg.indexOf('>', svg.indexOf('<svg '))
const content = `{@html \`${escapeSvelte(svg.slice(openTagEnd, closeTagStart))}\`}`
```
start with `openTagEnd` will include extra '>', should be 
```
const content = `{@html \`${escapeSvelte(svg.slice(openTagEnd + 1, closeTagStart))}\`}`
```

![image](https://user-images.githubusercontent.com/5292688/139636394-520a2d99-585d-44c4-b0ee-84c2bf013016.png)

**Comment by antfu** [comment]
Nice spotting, mind creating a PR? Thanks

**Comment by RyanYANG52** [comment]
> Nice spotting, mind creating a PR? Thanks
just saw it, next time😀
