### ISSUE TITLE
feat: custom icon compiler 

### ISSUE THREAD

**Issue by dominikg** [antfu/unplugin-icons#111]
As described in https://github.com/antfu/unplugin-icons/issues/109  there are situations where Application built in compiler based frameworks want to utilize custom icon components.

Thess custom compilers could be provided inline in the plugin config or via 3rd party packages.
To enable using them the `compiler: string` option could be changed to allow  passing a compiler function directly.

eg

```js
Icons({
  compiler: svg => { const compiledSvg='do stuff'; return compiledSvg;}
})
```

```js
import customCompiler from 'some-package'
Icons({
  compiler: customCompiler()
})
```

**Comment by userquin** [comment]
I'll take a look when I have time...
