### ISSUE TITLE
Nuxt 3 module

### ISSUE THREAD

**Issue by leon0399** [antfu/unplugin-icons#114]
How to provide components: https://v3.nuxtjs.org/docs/directory-structure/components#library-authors

Examples:
- https://github.com/windicss/nuxt-windicss/tree/main/packages/nuxt-windicss
- https://github.com/posva/pinia/tree/v2/packages/nuxt

**Comment by joel-wenzel** [comment]
Unplugin as shown in the documentation for vue3 still works with nuxt 3.

```
import Icons from 'unplugin-icons/vite'
import IconsResolver from 'unplugin-icons/resolver'
import Components from 'unplugin-vue-components/vite'
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    build: {
        transpile: ['tslib', '@apollo/client', 'ts-invariant']
    },
    buildModules: [
        'nuxt-windicss',
        ['unplugin-icons/nuxt', { /* options */ }],

    ],
    router: {
        prefetchLinks: true,
    },
    vite: {
        plugins: [
            Components({
                resolvers: IconsResolver(),
            }),
            Icons(),
        ]
    }

})
```

**Comment by antfu** [comment]
#63

**Comment by mustafafrw** [comment]
what if we set the vite: false in the nuxt config and use webpack? How can we add these resolvers?

**Comment by zhouzilong2020** [comment]
>
Thanks so much for this, but there is a minor mistake Should be ``` resolvers: [IconsResolver()]```

> Unplugin as shown in the documentation for vue3 still works with nuxt 3.
> 
> ```
> import Icons from 'unplugin-icons/vite'
> import IconsResolver from 'unplugin-icons/resolver'
> import Components from 'unplugin-vue-components/vite'
> import { defineNuxtConfig } from 'nuxt3'
> 
> // https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
> export default defineNuxtConfig({
>     build: {
>         transpile: ['tslib', '@apollo/client', 'ts-invariant']
>     },
>     buildModules: [
>         'nuxt-windicss',
>         ['unplugin-icons/nuxt', { /* options */ }],
> 
>     ],
>     router: {
>         prefetchLinks: true,
>     },
>     vite: {
>         plugins: [
>             Components({
>                 resolvers: IconsResolver(),
>             }),
>             Icons(),
>         ]
>     }
> 
> })
> ```

Thanks so much for this, but there is a minor mistake: 
```
 resolvers: IconsResolver() //  resolvers: [ IconsResolver()]
```
