### ISSUE TITLE
How to used nuxt 3 with auto import ?

### ISSUE THREAD

**Issue by productdevbook** [antfu/unplugin-icons#118]

**Comment by antfu** [comment]
#63 - I'd suggest using UnoCSS on Nuxt 3.

**Comment by productdevbook** [comment]
> #63 - I'd suggest using UnoCSS on Nuxt 3.

There are tailwindcss and @apply codes in the project. I guess we can't switch to UnoCSS.

**Comment by productdevbook** [comment]
2. questions

```
 buildModules: [
    [
      'unplugin-icons/nuxt',
      {
        defaultClass: 'w-7 h-7 inline-block',
        customCollections: {
          red: FileSystemIconLoader('assets/icons'),
        },
      },
    ],
  ],
  ```
`<red-mdi-book />` [Vue warn]: Failed to resolve component: red-mdi-book

**Comment by antfu** [comment]
> There are tailwindcss and @apply with scss used codes in the project. I guess we can't switch to UnoCSS.

I can have UnoCSS work with Tailwind or other preprocessors by just enabling the icons preset

**Comment by antfu** [comment]
Auto import for Nuxt is ready - that's what #63 is for
