### ISSUE TITLE
error cannot find type definition file with typescript 4.5

### ISSUE THREAD

**Issue by zynth17** [antfu/unplugin-icons#119]
![image](https://user-images.githubusercontent.com/45350572/142997233-f6c80c5d-764c-4ec9-b338-7f66f514fe16.png)

another related issue [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages/issues/118)

**Comment by userquin** [comment]
see https://github.com/antfu/unplugin-icons#frameworks, expand `Vue3`:
```json
// tsconfig.json
{ 
  "compilerOptions": {
    "types": [
      "unplugin-icons/types/vue",
    ]
  }
}
```

**Comment by zynth17** [comment]
> see https://github.com/antfu/unplugin-icons#frameworks, expand `Vue3`:
> 
> ```json
> 
> // tsconfig.json
> 
> { 
> 
>   "compilerOptions": {
> 
>     "types": [
> 
>       "unplugin-icons/types/vue",
> 
>     ]
> 
>   }
> 
> }
> 
> ```

yes already did that and still got the error. like i said its okay with typescript v4.4.x and will only occur on typescript 4.5.x

**Comment by mythz** [comment]
Same issue for me, typescript 4.5.2 failed with build errors  Cannot find module '~icons/...' or its corresponding type declarations.

Had to revert to typescript 4.4.4 to resolve the issue

**Comment by userquin** [comment]
ok, I'll take a look later...

**Comment by userquin** [comment]
@zynth17 @mythz I'll craete a project from `vitesse` template and update `ts` dep to check this, stay turned, later I'll update the docs

**Comment by userquin** [comment]
There is something wrong on the types, we need to review them.

@antfu see this, it seems we need to update the `package.json`, something  has changed (also applies to `vite-plugin-pages/client`):
```bash
======== Resolving type reference directive 'unplugin-icons/types/vue', containing file 'F:/work/projects/quini/GitHub/vitesse-with-ts-4.5/__inferred type names__.ts', root directory 'F:/work/projects/quini/GitHub/vitesse-with-ts-4.5/node_modules/@types'. ========
Resolving with primary search path 'F:/work/projects/quini/GitHub/vitesse-with-ts-4.5/node_modules/@types'.
Directory 'F:/work/projects/quini/GitHub/vitesse-with-ts-4.5/node_modules/@types/unplugin-icons/types' does not exist, skipping all lookups in it.
Looking up in 'node_modules' folder, initial location 'F:/work/projects/quini/GitHub/vitesse-with-ts-4.5'.
File 'F:/work/projects/quini/GitHub/vitesse-with-ts-4.5/node_modules/unplugin-icons/package.json' exists according to earlier cached lookups.
Export specifier './types/vue' does not exist in package.json scope at path 'F:/work/projects/quini/GitHub/vitesse-with-ts-4.5/node_modules/unplugin-icons'.
Directory 'F:/work/projects/quini/GitHub/node_modules' does not exist, skipping all lookups in it.
Directory 'F:/work/projects/quini/node_modules' does not exist, skipping all lookups in it.
Directory 'F:/work/projects/node_modules' does not exist, skipping all lookups in it.
Directory 'F:/work/node_modules' does not exist, skipping all lookups in it.
Directory 'F:/node_modules' does not exist, skipping all lookups in it.
======== Type reference directive 'unplugin-icons/types/vue' was not resolved. ========
```

Clone the repo here https://github.com/userquin/vitesse-with-ts-4.5 and run `pnpm install && tsc --traceResolution > ts-traceres.txt`, you will get this error (see it at hte bottom of the txt file). It will generate all `js` for each `ts` module:
```bash
error TS2688: Cannot find type definition file for 'unplugin-icons/types/vue'.
  The file is in the program because:
    Entry point of type library 'unplugin-icons/types/vue' specified in compilerOptions
error TS2688: Cannot find type definition file for 'vite-plugin-pages/client'.
  The file is in the program because:
    Entry point of type library 'vite-plugin-pages/client' specified in compilerOptions
```

**Comment by peter50216** [comment]
This might be similar issue to https://github.com/hannoeru/vite-plugin-pages/issues/118

**Comment by userquin** [comment]
uhmmm, I'll take a look later

**Comment by dima-f1** [comment]
Any updates on this? Have the same error but with **unplugin-icons/types/react**
```
error TS2688: Cannot find type definition file for 'unplugin-icons/types/react'.         
  The file is in the program because:                                                    
    Entry point of type library 'unplugin-icons/types/react' specified in compilerOptions
                                                                                         
  tsconfig.json:20:13                                                                    
    20             "unplugin-icons/types/react"                                          
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.
```

**Comment by replygirl** [comment]
suh dudes. go to `<your node_modules store>/unplugin-icons/package.json` and add something like this on line 41:

```
"./types/react": {
  "types": "./types/react.d.ts"
},
```

see #129
