### ISSUE TITLE
icon component be a string from server

### ISSUE THREAD

**Issue by pincman** [antfu/unplugin-icons#132]
If i have an menu config from server,the icon is string not component,how to use it?like [this](https://docs.iconify.design/icon-components/react/)

**Comment by antfu** [comment]
https://github.com/antfu/unplugin-icons#custom-icons

You can write your down function to request them.

**Comment by pincman** [comment]
@antfu Sorry, I may not have made it clear, the menu data object like 
```javascript
[{
    icon: 'xxx',
    name: 'dashboard',
},
{
    icon: 'yyy',
    name: 'signin',
},
]
```
and in jsx,how to import ionify icon?
```jsx
const icon = menu.icon
<Icon name={icon} />
```
this component only can
```jsx
<XXX />
```

**Comment by antfu** [comment]
Sorry no if they can't be determined at build time https://github.com/antfu/unplugin-icons/issues/5

You can consider using Iconify's runtime

**Comment by pincman** [comment]
I think this is indeed impossible, because the dynamic icon obtained from the server is unpredictable, so it is impossible to have a local icon. Maybe the official api from ionify is the best way
Another question, can local static icons only be used in the way of components?
How can it be loaded on demand like the following? The purpose of this is to encapsulate a unified `Icon` component to facilitate integration with [iconfont](https://www.iconfont.cn/), `antd/icon` and other libraries

```jsx
<Icon name={icon} {...rest} />
```

**Comment by pincman** [comment]
@antfu finally,component like 
```jsx
const Icon: FC<IconFontPropsType | SvgPropsType | AntdPropsType | IonifyPropsType> = (props) => {
    // it's by **unplugin-icons**
    if (props.type === IconType.IONIFY) return <Ionify {...omit(props, ['children'])} />;
   // others
    if (props.type === IconType.Antd) return <AntdIcon {...props} />;
    if (props.type === IconType.ICONFONT) return <IconFont {...props} />;
    return <SvgIcon {...(props as SvgPropsType)} />;
};
export default Icon;

```
