### ISSUE TITLE
Setting the icon properties for individual icons.

### ISSUE THREAD

**Issue by Fanna1119** [antfu/unplugin-icons#136]
it is known that we can set the properties like this
`<icon-account-box style="font-size: 2em; color: red"/>`
or globally in the settings for all icons like this:

```js

Icons({
  scale: 1.2, // Scale of icons against 1em
  defaultStyle: '', // Style apply to icons
  defaultClass: '', // Class names apply to icons
  compiler: null, // 'vue2', 'vue3', 'jsx'
  jsx: 'react' // 'react' or 'preact'
})
```

Sometimes when working with ui frameworks and custom components we would do the following:

```js

import unlocked from '~icons/carbon/unlocked'
import locked from '~icons/carbon/locked'

<el-switch :active-icon="locked" :inactive-icon="unlocked"></el-switch>

```
the problem is that the icon is too small by default and i can't set the size here.

I was thinking of different ways to perhaps approach this problem.

1. Maybe an ability to alternatively  set the attributes like this?
```js
import unlocked from '~icons/carbon/unlocked?width=50;color=blue'

```

2. or perhaps a helper somehow 

```js
return {
unlocked: iconAttrs(unlocked, {width: 50, color: blue})
}
```

**Comment by userquin** [comment]
I'll take a look via configuration, later via url params and also including the option to force `background-img`  or `mask`.

**Comment by userquin** [comment]
First approach from configuration, testing also query params:

![imagen](https://user-images.githubusercontent.com/6311119/147371461-d4fd5153-aa6b-40ce-9956-3d46f050e134.png)

![imagen](https://user-images.githubusercontent.com/6311119/147371447-4761cb42-ab03-4318-b5ef-66b7678fe3a4.png)

**Comment by userquin** [comment]
with query params:

![imagen](https://user-images.githubusercontent.com/6311119/147371695-44ec44bc-f7e0-4e5d-98b7-9006610393d5.png)

![imagen](https://user-images.githubusercontent.com/6311119/147371689-ed842494-eb3a-41f7-afb4-43d38b62af49.png)
