### ISSUE TITLE
possible to preemptively generate `AutoImport`'s `d.ts` file?

### ISSUE THREAD

**Issue by Enteleform** [antfu/unplugin-icons#148]
### Use Case

Generate all possible types based on `Icons` & `IconsResolver` settings.

This would allow developers to take advantage of IntelliSense auto-completion, reducing the need to reference [Iconify](https://icon-sets.iconify.design).

**Comment by mtunski** [comment]
+1

**Comment by antfu** [comment]
Note that by default it supports all 30,000+ icons, generating that would be very inefficient. For IDE support you might want https://github.com/antfu/vscode-iconify
