### ISSUE TITLE
[Feature]Support pass `raw` in query to get raw string

### ISSUE THREAD

**Issue by CzBiX** [antfu/unplugin-icons#151]
My project is mixed with react and html(due to third party library).
I want to get the svg content of icon, so I can pass it as html to other library.

Is it possible to support pass `raw` to use the raw compiler?
```js
import IconSvg from '~/icons/mdi/add?raw'
```

I modified some of code which can achieved the results I wanted.
But I think it's too tricky for the public, I wish there will be official support for this feature.

**Comment by userquin** [comment]
@CzBiX this is what you need?

![imagen](https://user-images.githubusercontent.com/6311119/153637759-666c80a4-7a2e-4368-82fd-592a7219e3d2.png)

**Comment by CzBiX** [comment]
That's exactly what I wanted.
There is a small issue in your picture, it has an extra `raw` attribute on `svg` element.

**Comment by userquin** [comment]
@CzBiX yeah, removed on the PR code

**Comment by userquin** [comment]
@CzBiX I have included how to use it on react example, is there a better way to do it, right now using `dangerous...` attr?
