### ISSUE TITLE
Support to change `~icons` alias

### ISSUE THREAD

**Issue by EstebanBorai** [antfu/unplugin-icons#164]
It would be great to have support for defining a custom alias when configuring unplugin icons, this would help in cases where you want to follow library or framework conventions.

For instance it's commonly seen in ReactJS codebases _import aliases_ prefixed with `@` for example: `@project-name`, or in case you want to alias the path to the `components` directory you could do`@components`. In Svelte you find the dollar sign symbol similarly, for instance `$lib` for the SvelteKit's `lib` directory or you could have a custom for internationalization such as: `$i18n`.

In my use case I'm using SvelteKit with this library and I would like to have `$icons` instead of `~icons`, so all of my import paths are prefixed under the same symbol.

**Comment by silasabbott** [comment]
For SvelteKit, with the new 'alias' option in `svelte.config.js`, you can do this easily:

<img width="335" alt="Screen Shot 2022-07-12 at 3 23 24 PM" src="https://user-images.githubusercontent.com/8752644/178606643-ca394943-c9dd-4058-9cc1-35811a0f9786.png">

**Comment by antfu** [comment]
When using custom aliases you need to add .d.ts to handle it properly
https://github.com/antfu/unplugin-icons/tree/main/types

**Comment by silasabbott** [comment]
Oh yep, thanks, I had just figured that out before I seeing this. For anyone that comes across this, here's what I added in SvelteKit:

```js
// svelte.config.js

const config = {
  kit: {
    alias: {
      $icons: '~icons'
    }
  }
}

```

```ts
// src/global.d.ts

declare module '$icons/*' {
  import { SvelteComponentTyped } from 'svelte'
  export default class extends SvelteComponentTyped<svelte.JSX.IntrinsicElements['svg']> { }
}
```

I just copied the declaration from the [**svelte.d.ts**](https://github.com/antfu/unplugin-icons/blob/8353b872cf350203f156730844892ccd5350a2b5/types/svelte.d.ts#L5) file and changed `~icons/*` to my custom alias.

Using `virtual:icons` didn't work for me as of `@sveltejs/kit@1.0.0-next.370` (SvelteKit tries to transform it into an absolute path).

**Comment by cdtconsulting** [comment]
You can import the types files in `App.d.ts`.

```ts
import 'unplugin-icons/types/svelte';
```

**Comment by teenjuna** [comment]
For SvelteKit users who use Node adapter, here's how I managed to do it:

1. Add alias in vite config
```typescript
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import Icons from 'unplugin-icons/vite';

export default defineConfig({
	plugins: [
		sveltekit(),
		Icons({
			compiler: 'svelte'
		})
	],
	resolve: {
		alias: [
			{
				find: '$icons',
				replacement: '~icons'
			}
		]
	}
});
```
2. Create a `global.d.ts` (for some reason, updating `app.d.ts` doesn't work) file with the following content:
```typescript
declare module '$icons/*' {
	import { SvelteComponentTyped } from 'svelte';
	export default class extends SvelteComponentTyped<svelte.JSX.IntrinsicElements['svg']> {}
}
```

The first step makes build work, the second makes language server recognise the imports.

**Important note**: adding alias in `svelte.config.js` breaks the build (not dev server) - compiler tries to find `~icons` directory in my project root...
