### ISSUE TITLE
Possibility to generate SVG/access body instead of component

### ISSUE THREAD

**Issue by taffit** [antfu/unplugin-icons#165]
Hello,

and first of all: thank you for this wonderful software which leverages the usage of the already marvellous iconify even more.

I have a problem currently, where I need to use the icons in the JavaScript-code of a SvelteKit-application in order to generate some html. However I couldn't find any possibility to easily generate the SVG out of an imported icon. Instead I get a `ProxyComponent`. I guess that I could switch the `compiler`-setting to `'none'` or `'raw'`, but as I am using the icons in 100 different places as icon-components, I can't just turn it off.

I scanned the documentation multiple times and also took a look at the sources and methods of the `ProxyComponent`, but couldn't find a way to generate the SVG or access the body/data of the icon. Is there a method I just missed? As said, I use it in a lot of Svelte-components to load icons.

The (simplified) usage I imagine would be as follows (instead I'm currently just saving the whole SVG as string):
```javascript
import IonSearchIcon from '~icons/ion/search';

let searchIcon = `<div><svg>${IonSearchIcon.body}</svg></div>`;

// Some further processing
```

Could you help me put me on the right path?

Again, thanks a lot for the library, it simplified my development *a lot*.

**Comment by userquin** [comment]
@taffit adding `?raw` is what you need? https://github.com/antfu/unplugin-icons/issues/151

**Comment by taffit** [comment]
@userquin Exactly something like this! Would be great: still flexible to add every icon, but also to chose in which format. This would fit my needs perfectly!

**Comment by userquin** [comment]
@taffit I only add the  `raw` compiler, since you can use only one compiler from configuration options, and `none` will be only usable from internal compilers.

Yes, the examle is on `vue3` example but you can also apply the same code to your `svelte/sveltekit` sfc, the iimport will just export the svg icon as default, so you can use it where you want.

**Comment by userquin** [comment]
@taffit I'll add an example on `svelte/sveltekit` examples (also for each fw)

**Comment by taffit** [comment]
@userquin Thanks a lot for the quick response! Fabulous! Exactly and easily and quickly solving the issue! Perfect! Thank you once more!
