### ISSUE TITLE
Default icon size 1.2em differs from iconify default icon size 1em

### ISSUE THREAD

**Issue by awacode21** [antfu/unplugin-icons#171]
Regarding the [iconify docs](https://docs.iconify.design/icon-components/vue/dimensions.html) the icons should default to width="1em" and height="1em".
Which it does when using iconify directly.

But when using the iconify icons by unplugin-icons they default to width="1.2em" and height="1.2em". So it differs from documentation.

Indeed this is not so important as you can set the "right" sizes by yourself, but i would like to mentioned it, because the difference is nowhere documented, or i was not able to find it.

**Comment by antfu** [comment]
It's intentional and documented here https://github.com/antfu/unplugin-icons/blob/e4f49809756f55e9cd46b03de55eaee0876996da/src/types.ts#L10-L15
