### ISSUE TITLE
Rendered SVG's ignore 'scale' from 0.13.4 to 0.14 (and defaults to 1em)

### ISSUE THREAD

**Issue by qgates** [antfu/unplugin-icons#178]
Code:

```ts
  <button class="btn-fixed bg-green-500 print:hidden" @click="$router.push({name: 'new'})">
    <icn-fa-solid-pencil-alt class="fa-icon text-xl" />
  </button>
```

In versions 0.13.4 and below, the icon is rendered with width and height at 1.2em, the default `scale` setting for options as [specifed in the docs](https://github.com/antfu/unplugin-icons#options). Since 0.14 the icon is rendered at with width and height of 1em. Changing `scale` no longer works. This affects all icons (and breaks) my project. Is this expected behaviour or a breaking bug?

Before (<=0.13.4):

![image](https://user-images.githubusercontent.com/4213509/159516611-8bda6aff-71cf-4cd3-9518-72e1b5ecdd3d.png)

After (0.14.0):

![image](https://user-images.githubusercontent.com/4213509/159517078-13770a4b-da05-43ad-be9c-697095de151c.png)

**Comment by userquin** [comment]
@qgates we've update the plugin to use universal icon loader, it seems we need to change some logic, fixing it

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/159551972-d9865d1c-bdc4-41dc-87d6-f3215fc3f581.png)

**Comment by qgates** [comment]
@userquin looks good 👍 Any way to test on the PR or do I just wait for @antfu to release?

**Comment by qgates** [comment]
Many thanks tested all working correctly 👍
