### ISSUE TITLE
Auto Import for SvelteKit (or VSCode import suggestion)

### ISSUE THREAD

**Issue by SarcevicAntonio** [antfu/unplugin-icons#187]
Like I mentioned here https://github.com/antfu/unplugin-icons/issues/142#issuecomment-1054581854, Im trying to use auto-import with SvelteKit and wondered if it is supported at all.

Or if VSCode could somehow suggest imports of something like `< IconMdiAccountBox/>` I would be happy also very happy.

What can we do to get this working/supported?

**Comment by userquin** [comment]
what works is the auto import, we haven't a `unplugin-vue-components` for svelte, it only works only with `vue` and `react` see https://github.com/antfu/unplugin-icons#auto-importing

**Comment by userquin** [comment]
uppps, wrong button, sorry

**Comment by silasabbott** [comment]
> what works is the auto import

Are you saying we can manually set up auto-import in Svelte? Auto import is so convenient—I'd love to be able to use it in my Svelte projects

**Comment by userquin** [comment]
@silasabbott yes you can use auto import in suelte and sveltekit,  check the examples folder in the auto import repo
