### ISSUE TITLE
how to create a dynamic list of icons

### ISSUE THREAD

**Issue by modex98** [antfu/unplugin-icons#189]
How to print a list of icons just from an array   for example `[{ name: "edit" }, { name: "settings" }]`

and i get 
```
<i-mdi-edit />
<i-mdi-settings />
```

and in the browser it really renders the wanted icon

**Comment by userquin** [comment]
@modex98 you can try `import.meta.glob` or `import.meta.globEager` using `raw` option, but you'll need to use some directive to render the svg icon: https://github.com/antfu/vite-plugin-pwa/issues/257#issue-1192505746

**Comment by serfend** [comment]
when i use `import.meta.glob` or `import.meta.globEager`
its warn that `[plugin:vite:import-analysis] Invalid glob import syntax: pattern must start with "." or "/" (relative to project root) or alias path`

**Comment by serfend** [comment]
NOT SUPPORT THIS WAY for [there is no way to infer a component from a dynamic string](https://github.com/antfu/unplugin-icons/issues/5#issuecomment-1005887483)
