### ISSUE TITLE
Broken `vite` typing for `Plugin` in `dist`

### ISSUE THREAD

**Issue by prescience-data** [antfu/unplugin-icons#191]
When attempting to build, I receive the following error:
```
Error: node_modules/unplugin-icons/dist/vite.d.ts:4:60 - (TS2552) Cannot find name 'Plugin$1'. Did you mean 'Plugin'?

```

Upon inspection, there seems to be a broken link with Vite when building (`node_modules/unplugin-icons/dist/vite.d.ts`)

![image](https://user-images.githubusercontent.com/65471523/165883550-de8d7a4c-2989-4616-8365-e4284731ab2b.png)

**Comment by antfu** [comment]
Should be fixed
