### ISSUE TITLE
Using in vue 2 application with events

### ISSUE THREAD

**Issue by gitgkk** [antfu/unplugin-icons#196]
Hi,
Glad to see a project with such a large collection of icons.
Does this library support mouse events on icons like onHover, onClick ?
Any examples with vue 2, vuetify?

Thanks,
Kashyap

**Comment by userquin** [comment]
@gitgkk yes, it will generate vue component for each requested icon, but, you will not be able to change the icon on `@mouseover`

![imagen](https://user-images.githubusercontent.com/6311119/167492242-c53f8d4f-e840-4363-ba65-4a340587ef18.png)

**Comment by kamilic** [comment]
> @gitgkk yes, it will generate vue component for each requested icon, but, you will not be able to change the icon on `@mouseover`
> 
> ![imagen](https://user-images.githubusercontent.com/6311119/167492242-c53f8d4f-e840-4363-ba65-4a340587ef18.png)

It seems that you are using vue3 in this example. I found the same problem, @click will not attach event listener to svg element on vue2 project.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by bmulholland** [comment]
This is still an issue. Filed https://github.com/unplugin/unplugin-icons/issues/329 with a minimal repro.
