### ISSUE TITLE
currentColor of the custom icon is not suitable for most cases

### ISSUE THREAD

**Issue by hairyf** [antfu/unplugin-icons#202]
I found a tool, maybe the documentation should remind developers to use
https://github.com/svg/svgo

**Comment by userquin** [comment]
@TuiMao233 have you read this entry https://github.com/antfu/unplugin-icons#advanced-custom-icon-set-cleanup?

**Comment by TuiMao233** [comment]
Of course, but for example custom svg's currentColor, usually this is not applicable

```ts
svg.replace(/^<svg /, '<svg fill="currentColor" ')
```

Most svg's are complex, maybe the documentation should note that we can use [svgo](https://github.com/svg/svgo) for better processing

![image](https://user-images.githubusercontent.com/49724027/178892118-0d69cf3f-0c4d-4b84-82fc-30015bdcabcd.png)
