### ISSUE TITLE
Auto-import based on prop binding pattern

### ISSUE THREAD

**Issue by TechAkayy** [antfu/unplugin-icons#203]
Thanks for this amazing plugin. I'm using auto-import via unplugin-components, unicons (prefix is 'uil') iconset in the below example (https://stackblitz.com/github/techakayy/vuetify3-beta-unplugin-icons?file=src%2FApp.vue). 

So, basically, `<i-uil-android>` will auto-import just fine as it uses the `{prefix}-{collection}-{icon}` tag pattern.

But, if I'm binding the icon as a prop (`uilShoppingCart` in the below example), then looks like I need to manually import the icon. 

Is it possible to support auto-import based on prop-binding pattern as well, for example `{prefix}{Collection}{Icon}` (camelCase equivalent)? 

![image](https://user-images.githubusercontent.com/73772701/169501050-5c31de9c-b881-42ef-be98-6fb7f83dcdfa.png)

**Comment by userquin** [comment]
@TechAkayy you can use the `v-alert` slots: https://stackblitz.com/edit/github-dranvy?file=src%2FApp.vue

You should also file an issue on vuetify: the prepend slot will not add the additional `i`, so the docs are wrong or it is a `bug`: https://next.vuetifyjs.com/en/api/v-alert/#slots

**Comment by TechAkayy** [comment]
Many thanks @userquin. Yes, VAlert allows adding icons via slot. But, not all vuetify components supports icons via slot, for eg, [VBtn](https://next.vuetifyjs.com/en/api/v-btn/#slots), [VAvatar](https://next.vuetifyjs.com/en/api/v-avatar/#slots) etc, hence the above request.

**Comment by userquin** [comment]
@TechAkayy https://discord.com/channels/340160225338195969/660898563139567625/977160663057195038

**Comment by userquin** [comment]
@TechAkayy you can use `preset-icons` from `UnoCSS` instead: 
- https://github.com/unocss/unocss/tree/main/packages/preset-icons
- https://uno.antfu.me/?s=i-twemoji-frog

**Comment by TechAkayy** [comment]
Ohh woww.. thanks bunch @userquin :-) Much appreciated. Unocss is new to me, going to explore it tonight!

**Comment by userquin** [comment]
`vuetify` should add a way to use custom icons via slot instead prop

**Comment by TechAkayy** [comment]
Unocss icons preset is an amazing combo for vuetify :-) Thanks a lot for suggesting it.. 

https://stackblitz.com/github/techakayy/vuetify3-beta-unocss-icons

![image](https://user-images.githubusercontent.com/73772701/169534832-617800f3-563b-4bc3-a5c1-25b983e77b2c.png)

**Comment by TechAkayy** [comment]
> 

Added feature request in vuetify - https://github.com/vuetifyjs/vuetify/issues/15164
