### ISSUE TITLE
使用nvm导致的问题

### ISSUE THREAD

**Issue by hlgf** [antfu/unplugin-icons#208]
不知道是不是使用了nvm的问题,使用  Icons({autoInstall: true})会报错Couldn't find a package.json ,然后无法下载成功[http://test--web.test.upcdn.net/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220609100821.png](url)

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by hlgf** [comment]
``[图片](http://test--web.test.upcdn.net/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220609100821.png)
