### ISSUE TITLE
webstorm nuxt3  Cannot resolve directory '~icons' 

### ISSUE THREAD

**Issue by LUDA0831** [antfu/unplugin-icons#213]
![image](https://user-images.githubusercontent.com/45849881/174542449-705d31a1-b76a-4c1b-a4c8-c9951f46446a.png)
## webstorm error Cannot resolve directory '~icons' 
webstorm Version 2022.1.2
nuxt Version 3.0.0-rc.4

**Comment by talaxasy** [comment]
Any help?

**Comment by darianstlex** [comment]
```
declare module '~icons/*' {
  import { FunctionalComponent, SVGAttributes } from 'vue'
  const component: FunctionalComponent<SVGAttributes>
  export default component
}
```

**Comment by darianstlex** [comment]
or: https://github.com/antfu/unplugin-icons/issues/204#issuecomment-1157570814

**Comment by talaxasy** [comment]
This issue can be closed

**Comment by ennioVisco** [comment]
@LUDA0831 how did you solve it? I still have the issue :/

**Comment by ennioVisco** [comment]
> > @LUDA0831 how did you solve it? I still have the issue :/
> 
> > declare module '~icons/*' {
> > import { FunctionalComponent, SVGAttributes } from 'vue'
> > const component: FunctionalComponent
> > export default component
> > }
> 
> @ennioVisco this can be solved

Ok, thanks, but where did you put it?

**Comment by LUDA0831** [comment]
@ennioVisco 

![image](https://user-images.githubusercontent.com/45849881/190322808-635d39c7-af78-4ab0-a4ff-f4230804f689.png)

**Comment by anburocky3** [comment]
When i have any other declaration then the `~icons/*` it fails. Why is that?

**Comment by dongnaebi** [comment]
> declare module '~icons/*' {
  import { FunctionalComponent, SVGAttributes } from 'vue'
  const component: FunctionalComponent<SVGAttributes>
  export default component
}

can we add it to README.md?
