### ISSUE TITLE
Icons auto-import for Nuxt 3

### ISSUE THREAD

**Issue by ennioVisco** [antfu/unplugin-icons#219]
Inspired by https://github.com/antfu/unplugin-icons/issues/213, it would be nice if there was a way to perform icons auto-import in nuxt 3.

However, the Nuxt 3 docs doesn't say how to implement it: https://v3.nuxtjs.org/guide/concepts/auto-imports#directory-based-auto-imports.

**Comment by antfu** [comment]
There is currently no way to do that in Nuxt, pending PRs for Nuxt 2:

- https://github.com/antfu/unplugin-icons/pull/63
- https://github.com/nuxt/components/pull/234

While we haven't discussed about we should implement it in Nuxt 3. Ideally, it would be better for Nuxt to expose a resolve function to match with unknown components similar to `unplugin-vue-components`. /cc @pi0

While on the other hand, I personally think [UnoCSS's icon solution](https://antfu.me/posts/icons-in-pure-css) is generally better than this plugin (which works with both Nuxt 2 and 3 from day one) and I have moved most of my projects using it.

**Comment by HayateLaTech** [comment]
While I appreciate the blog-post about UnoCSS and it being a solution that actually works, I think I'll write a quick tutorial how to make it all work in Nuxt 3 directly.

Like seriously xD I've been trying for 3 days straight to make unplugin-icons work in Nuxt 3 and this has been giving me so many headaches.. ;w; and finding the solution the one and only antfu also switched for is hella difficult xD
That basically the same outcome can be achieved so easily blows my mind x3

npm
`npm i -D @unocss/nuxt @unocss/preset-icons @iconify/json`

nuxt.config.ts
```js
modules: [
    '@unocss/nuxt',
],
unocss: {
    // presets
    uno: false, // enabled "@unocss/preset-uno"
    icons: true, // enabled "@unocss/preset-icons"
    attributify: false, // enabled "@unocss/preset-attributify"
    
    // core options
    shortcuts: [],
    rules: [],
},
```

components/somefolder/something.vue
```html
<template>
  <div>
    <div class="i-vscode-icons:file-type-json"></div>
  </div>
</template>
```

### Useful Tools

- [Iconify Intellisense (VS Code Extension)](https://marketplace.visualstudio.com/items?itemName=antfu.iconify)
- [Iconify IconSets List](https://icon-sets.iconify.design/)


And don't get me wrong, I really appreciate all the things you create - you make webdev so much more great.. but unplugin-icons and nuxt 3 and all the posts with half-assed vite solutions really drive me mad xD so I hope this post here can help ease some peoples minds too, finally ^w^

**Comment by ennioVisco** [comment]
> 

Thanks for the guide, I'm sure it will be useful to many.
I'm still puzzled about the div-based approach to be honest: I like the component-oriented approach, I think it looks cleaner and more intuitive, although I do recognize the benefits that @antfu cleverly points out in his article.

Moreover, while I can recognize the benefits of UnoCSS in an Atomic-CSS settings, I see little to no value when not using Atomic CSS, unfortunately. 

I prefer a different "composable" approach, based on SASS mixin, like in the example shown here:

```vue
<template>
    <button :class="$style['btn--dark']">Sample button</button>
</template>

<style module>
@use  "@/assets/css/settings";
 
.btn--dark {
    background-color: settings.background;
}
</style>
```

This is much more meaningful and relies an almost standard CSS syntax (instead of having to learn the atomic CSS unreadable meta-language that basically reproduces CSS)

**Comment by antfu** [comment]
Thanks for the detailed guide @HayateLaTech!

If you still prefer to use dev based approach you may also try with https://twitter.com/Atinux/status/1566908478286958593.

**Comment by husayt** [comment]
I found unocss to be the most organic/holistic way to get icons working in line with tailwind syntax/dynamic icons/icon classes and etc. With that you don't need any other libraries.

You can have multiple styles for icons and most importantly this works in framework agnostic way i.e. across vue, react, svelte and etc
```
<div class="i-heroicons-solid:academic-cap" />
<div i-heroicons-solid:academic-cap />
<unoIcon i-heroicons-solid:academic-cap />
```



One tip: to get dynamic icons working just add them to safelist in unocss.config

**Comment by Idered** [comment]
This works for me in nuxt 3:

```ts
import { defineNuxtConfig } from 'nuxt'
import IconsResolver from 'unplugin-icons/resolver'
import Icons from 'unplugin-icons/vite'
import Components from 'unplugin-vue-components/vite'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig(async () => ({
  modules: [
    ['unplugin-icons/nuxt']
  ],
  vue: {
    template: {
      compilerOptions: {
        isCustomElement: (tag) => tag.startsWith('i-'),
      },
    },
  },
  vite: {
    plugins: [
      Components({
        resolvers: [IconsResolver()],
      }),
      Icons({}),
    ],
  },
}))
```

**Comment by ennioVisco** [comment]
> This works for me in nuxt 3:
> 
> ```ts
> import { defineNuxtConfig } from 'nuxt'
> import IconsResolver from 'unplugin-icons/resolver'
> import Icons from 'unplugin-icons/vite'
> import Components from 'unplugin-vue-components/vite'
> 
> // https://v3.nuxtjs.org/api/configuration/nuxt.config
> export default defineNuxtConfig(async () => ({
>   modules: [
>     ['unplugin-icons/nuxt']
>   ],
>   vue: {
>     template: {
>       compilerOptions: {
>         isCustomElement: (tag) => tag.startsWith('i-'),
>       },
>     },
>   },
>   vite: {
>     plugins: [
>       Components({
>         resolvers: [IconsResolver()],
>       }),
>       Icons({}),
>     ],
>   },
> }))
> ```

Closing: either adopt the quoted message, or the  official `nuxt-icon` [module](https://github.com/nuxt-modules/icon), or UnoCSS [icons preset](https://github.com/unocss/unocss/tree/main/packages/preset-icons/).
