### ISSUE TITLE
There are tsx and vue files in the project, can't both files be automatically imported?

### ISSUE THREAD

**Issue by wangrongding** [antfu/unplugin-icons#221]
In the .vue file, it works fine
```js
// vite.config.ts
IconsResolver({
  enabledCollections: ['ep']
})
```

But in tsx， I tried to write like this, but it didn't work😢

```js
// vite.config.ts
plugins: [
  Icons({
    jsx: 'react', // 'react' or 'preact'
    compiler: 'jsx', // 'vue2', 'vue3', 'jsx'
  }),
  // Api自动导入
  AutoImport({
    resolvers: [
      IconsResolver({
        prefix: 'i', // 图标前缀，默认为i
        enabledCollections: ['ep'],
        extension: 'jsx',
      }),
    ],
  }),
  // 按需导入组件
  Components({
    resolvers: [
      // 自动注册图标组件
      IconsResolver({
        prefix: 'i', // 图标前缀，默认为i
        extension: 'jsx',
        enabledCollections: ['ep'],
      }),
    ],
  }),
],
```

**Comment by userquin** [comment]
@wangrongding check `React/Solid` in the README: https://github.com/antfu/unplugin-icons#auto-importing

Also change the extension to `tsx`, you've `jsx` in your configuration.

**Comment by wangrongding** [comment]
> @wangrongding check `React & Solid` in the README: https://github.com/antfu/unplugin-icons#auto-importing
> 
> Also change the extension to `tsx`, you've `jsx` in your configuration.


However, if you change the `extension` to `tsx`, the automatic import of the .vue file will fail.

**Comment by wangrongding** [comment]
> @wangrongding use vue or tsx, it seems like a limitation here and on auto import (I think vue + jsx shouldn't work either)

Because some logic can be implemented very flexibly in tsx.
😢😢So, it can't be done?

**Comment by wangrongding** [comment]
@userquin  OK, thank you very much!👍🥰

**Comment by userquin** [comment]
@wangrongding can you put here your configuration?

**Comment by wangrongding** [comment]
> @wangrongding can you put here your plugin configuration?

ok~  

```js
import { defineConfig, loadEnv } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import * as path from 'path'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'

import Icons from 'unplugin-icons/vite'
import IconsResolver from 'unplugin-icons/resolver'
// https://vitejs.dev/config/

export default defineConfig((config) => ({
  plugins: [
    vue(),
    vueJsx(),
    Icons({
      jsx: 'react', // 'react' or 'preact'
      compiler: 'vue3', // 'vue2', 'vue3', 'jsx'
    }),
    // Api自动导入
    AutoImport({
      // 目标文件
      include: [
        /\.[tj]sx?$/, // .ts, .tsx, .js, .jsx
        /\.vue$/,
        /\.vue\?vue/, // .vue
        /\.md$/, // .md
      ],
      // 全局引入插件
      imports: ['vue', 'vue-router'],
      resolvers: [
        // 自动导入Element-Plus的Api
        ElementPlusResolver(),
        // 自动导入图标组件
        // 自动导入必须遵循名称格式 {prefix：默认为i}-{collection：图标集合的名称}-{icon：图标名称}
        // IconsResolver(),
        IconsResolver({
          prefix: 'i', // 图标前缀，默认为i
          enabledCollections: ['ep'],
          extension: 'tsx',
        }),
      ],
      // eslint报错解决方案
      eslintrc: {
        enabled: true, // Default `false`
        filepath: './.eslintrc-auto-import.json', // Default `./.eslintrc-auto-import.json`
        globalsPropValue: true, // Default `true`, (true | false | 'readonly' | 'readable' | 'writable' | 'writeable')
      },
    }),
    // 按需导入组件
    Components({
      dts: true, // enabled by default if `typescript` is installed
      resolvers: [
        // 自动注册图标组件
        IconsResolver({
          prefix: 'i', // 图标前缀，默认为i
          extension: 'tsx',
          enabledCollections: ['ep'],
        }),
        // 自动导入 Element Plus 组件
        ElementPlusResolver(),
      ],
    }),
  ],
}))
```

**Comment by wangrongding** [comment]
@userquin  OK, I'll try it~👍

It's a little weird to write.😂
When you update the version, I will rewrite the logic of this piece again.

**Comment by userquin** [comment]
@wangrongding 

maybe we need to add another Icons plugin, that's, one for vue and another for `tsx` and we also need to change the prefix on the resolvers

Instead having this:
```ts
Icons({
      jsx: 'react', // 'react' or 'preact'
      compiler: 'vue3', // 'vue2', 'vue3', 'jsx'
    }),
```

we should have this:
```ts
Icons({
   compiler: 'vue3',
}),
Icons({
   jsx: 'react',
   compiler: 'jsx'
}),
```

**Comment by wangrongding** [comment]
@userquin thank you, my friend.
However, you need to wait for a while, I will provide you with it when I get home from getting off work later~ 😂

**Comment by userquin** [comment]
@wangrongding I'll check your repro tonight when I get off work too

**Comment by wangrongding** [comment]
💖It's okay, this problem is not urgent, I am working on an open-source  `management back office`

The problem we are talking about is happening in this repository.
https://github.com/wangrongding/vue-super-admin/blob/main/src/layout/SideBar/Menu.tsx#L45

**Comment by userquin** [comment]
@wangrongding should be something like this?
![imagen](https://user-images.githubusercontent.com/6311119/178571487-febf42d7-062f-4a9b-ab38-3bcc4f44de5e.png)

**Comment by userquin** [comment]
@wangrongding check also this another commit, just removing the `i` prefix from the second resolver in components plugin:
https://github.com/userquin/vue-super-admin-unplugin-icons-221/commit/0c9205ec0f0ec43511e6a20eb0f8b774db3268ab

**Comment by wangrongding** [comment]
Wow! Thank you, my good man!💖

I apologize for not providing you with the minimum replica library in time after work yesterday.

I wish you a happy life and all the best👍
