### ISSUE TITLE
style tags in svg files are get omitted

### ISSUE THREAD

**Issue by erkage** [antfu/unplugin-icons#229]
### Describe the bug

The <style> tags inside .svg custom icons are get omitted when using them.

### Reproduction

https://stackblitz.com/edit/vue3-script-setup-with-vite-78wpsw?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 104.13 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.18 - ~/Library/pnpm/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cimchd** [comment]
I encountered the same problem when I tried to add custom duotone icons.

**Comment by chetzof** [comment]
Can confirm. Trying to use a custom-built svg logo. Style tag missing.

**Comment by userquin** [comment]
It seems it is a vue bug/issue, there is a workaround: https://github.com/vuejs/vue/issues/4144#issuecomment-258818137

https://stackblitz.com/edit/vue3-script-setup-with-vite-ptgwfc?file=vite.config.js,src%2Fassets%2Ficons%2Fasd.svg,src%2Fassets%2Ficons%2Fasd-workaround.svg,src%2FApp.vue

**Comment by erkage** [comment]
I close this now as it's an [issue in Vue](https://github.com/vuejs/vue/issues/4144#issuecomment-258818137) and there's a [workaround](https://stackblitz.com/edit/vue3-script-setup-with-vite-ptgwfc?file=vite.config.js,src%2Fassets%2Ficons%2Fasd.svg,src%2Fassets%2Ficons%2Fasd-workaround.svg,src%2FApp.vue):
```
<defs>
  <svg:style>
    #asd {
      color:red;
    }
  </svg:style>
</defs>
```

**Comment by erkage** [comment]
I close this now as it's an [issue in Vue](https://github.com/vuejs/vue/issues/4144#issuecomment-258818137) and there's a [workaround](https://stackblitz.com/edit/vue3-script-setup-with-vite-ptgwfc?file=vite.config.js,src%2Fassets%2Ficons%2Fasd.svg,src%2Fassets%2Ficons%2Fasd-workaround.svg,src%2FApp.vue):
```
<defs>
  <svg:style>
    #asd {
      color:red;
    }
  </svg:style>
</defs>
```
