### ISSUE TITLE
您好，请问如何在vite unplugin的情况下在component或者jsx中使用呢？求助！谢谢！

### ISSUE THREAD

**Issue by litchia** [antfu/unplugin-icons#230]
如题，求帮助！

**Comment by litchia** [comment]
在template中使用时，会自动编译成svg，但是component或者jsx中，只是会被当成一个标签。

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
