### ISSUE TITLE
Error parsing the introduction of fluent-emoji

### ISSUE THREAD

**Issue by Assone** [antfu/unplugin-icons#233]
### Describe the bug

The icon of fluent-emoji is referenced in the vite project, but the plugin will parse it as fluent's icon, causing the reference to fail.
It should resolve to the @iconify-json/fluent-emoji dependency, not to @iconify-json/fluent.
And vscode's plugin Iconify IntelliSense can't preview the fluent-emoji icons either.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jvs98n?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
    Memory: 333.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
I have it working using an alias for `fluent-emoji`, check the configuration: https://stackblitz.com/edit/vitejs-vite-qbzfu7?file=vite.config.ts

**Comment by Assone** [comment]
> I have it working using an alias for `fluent-emoji`, check the configuration: https://stackblitz.com/edit/vitejs-vite-qbzfu7?file=vite.config.ts

Thanks, it works. But vscode's plugin Iconify IntelliSense still doesn't work

**Comment by userquin** [comment]
> Thanks, it works. But vscode's plugin Iconify IntelliSense still doesn't work

I don't use VSCode, check if you can provide some configuration to the plugin...
