### ISSUE TITLE
cannot find package 'vue-template-es2015-compiler'

### ISSUE THREAD

**Issue by Hyphon** [antfu/unplugin-icons#234]
### Describe the bug

when upgrade to vue 2.7.10, project is not working as expected.

error is `Cannot find package 'vue-template-es2015-compiler' imported from /home/projects/vitejs-vite-vt4gdf/node_modules/local-pkg/index.mjs`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-vt4gdf?file=vite.config.ts

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@Hyphon @IreneBenito can you try using `vue3` compiler? https://stackblitz.com/edit/vitejs-vite-zyfhyg?file=vite.config.ts

**Comment by Hyphon** [comment]
> @Hyphon @IreneBenito can you try using `vue3` compiler? https://stackblitz.com/edit/vitejs-vite-zyfhyg?file=vite.config.ts

Its ok with `compiler: 'vue3'`, thx very much. 
Would there be a preset '2.7' ? Vue v2.7 with compiler vue3 is a little confused for me...

**Comment by userquin** [comment]
@Hyphon I'll update the README later, also checking if it is required, if so I'll create a new 2.7 compiler

**Comment by userquin** [comment]
@Hyphon https://github.com/antfu/unplugin-icons/pull/251

**Comment by Hyphon** [comment]
> @Hyphon #251

thank u :)
