### ISSUE TITLE
Cannot resolve directory '~icons'  in PHPStorm IDE

### ISSUE THREAD

**Issue by anburocky3** [antfu/unplugin-icons#235]
How to suppress or get rid of these IDE errors?

![image](https://user-images.githubusercontent.com/15264938/190178252-f10b79ff-f845-49fd-b050-6fa8d415b2cd.png)

Adding docs on that, in the readme, would be super helpful.

**Comment by userquin** [comment]
if not working try adding this to your `tsconfig.json`:
``` json
"compilerOptions": {
  "types": ["unplugin-icons/types/vue"]
}
```

**Comment by anburocky3** [comment]
I have already added the types in the `tsconfig.json` file.

I'm using Laravel with Vite, Where should i place the file `vite-env.d.ts`?

I placed in `root` as well as `resources/js/` both, didn't pick up that, same issue.

**Comment by userquin** [comment]
what's the content of your tsconfig.json file?

**Comment by anburocky3** [comment]
These are my `tsconfig.json`
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "es2020",
        "moduleResolution": "node",
        "strict": true,
        // Enable strict type-checking options
        "skipLibCheck": true,
        // Skip type checking of declaration files
        "noImplicitAny": false,
        // Bypass raising errors on `any` type
        "baseUrl": ".",
        "paths": {
            "@/*": [
                "./resources/js/*"
            ],
            "ziggy": [
                "vendor/tightenco/ziggy/dist/vue"
            ]
        },
        "types": [
            "vite/client",
            "node",
            "unplugin-icons/types/vue"
        ]
    },
    "include": [
        "resources/assets",
        "resources/js/**/*"
    ]
    // Frontend paths pattern
}

```

**Comment by userquin** [comment]
try adding the dts file inside resources folder and add "resources/**.d.ts" to the include entry.

have you configured TS in the IDE (IntelliJ screenshot)?

![imagen](https://user-images.githubusercontent.com/6311119/190191767-d46607d1-3509-41cf-a32c-da7c06148d65.png)

**Comment by userquin** [comment]
For example, Vue3 example resolving, but the react one missing (in both cases the IDE will go to the definition):

![imagen](https://user-images.githubusercontent.com/6311119/190193113-2c6abec1-6c0b-4e94-bceb-fbb9d72342b0.png)

**Comment by anburocky3** [comment]
This is what i did:
1. Created `vite-env.d.ts` inside `resources` directory with the following code.
```
/// <reference types="unplugin-icons/types/vue" />
```
2. Added the entry in the `tsconfig.json` file
```diff
    "include": [
        "resources/assets",
        "resources/js/**/*",
+        "resources/**.d.ts"
    ]
```
3. Yes, my Typescript is configured correctly like this.
![image](https://user-images.githubusercontent.com/15264938/190195365-2a4f28a0-9dd0-4dd8-960d-172f21eea274.png)

After all this, still: 
![image](https://user-images.githubusercontent.com/15264938/190195465-9ea809e1-9922-428b-a4d7-1750d4f437ff.png)

**Comment by LUDA0831** [comment]
You can refer to this issues #213

**Comment by anburocky3** [comment]
Thank you and it fixed the errors. Thank you.
