### ISSUE TITLE
why the vue-cli-service build error with v0.14.9?

### ISSUE THREAD

**Issue by sdklove00** [antfu/unplugin-icons#236]
### Describe the bug

```

 ERROR  Failed to compile with 1 error                                          

  Error: Child compilation failed:
  Module parse failed: Unexpected token (1:0)
  File was processed with these loaders:
   * ./node_modules/html-webpack-plugin/lib/loader.js
   * ./node_modules/unplugin/dist/webpack/loaders/load.js
  You may need an additional loader to handle the result of these loaders.
  > <!DOCTYPE html>
  | <html lang="">
  |   <head>
```

<img width="434" alt="image" src="https://user-images.githubusercontent.com/17194772/190307890-be4a53ae-66f6-4924-9dca-1aa9be5e3672.png">

> finnally，i find is the unplugin-icons v0.14.9 and unplugin-vue-component v0.22.7 problems, i use unplugin-icons v0.14.8 and unplugin-vue-component v0.22.4 is working.

### Used Package Manager

npm

**Comment by Inori-Lover** [comment]
face same problem

**Comment by Inori-Lover** [comment]
https://github.com/Inori-Lover/unplugin-icon-repo

**Comment by darianstlex** [comment]
seems the fix didn't solve the issue
