### ISSUE TITLE
🐞 Custom collection not work in `h()` by `collection:icon-name`

### ISSUE THREAD

**Issue by chioio** [antfu/unplugin-icons#245]
### Describe the bug

**Custom collection**: `app`
**File path**: `/assets/icons/trash.svg`

**Render function**
```ts
export const renderIcon = (
  icon: string,
  props: Record<string, unknown> = { size: 20 }
) => h(Icon, { icon, width: props.size, height: props.size, ...props })
```

**Error produce**
```ts
const a = {
  icon: () => renderIcon('app:trash')
}
```

**! But success using in template like `<i-app:trash />`**

### Reproduction

None

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 1.37 GB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/Library/Caches/fnm_multishells/25267_1653168489651/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/Library/Caches/fnm_multishells/25267_1653168489651/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
If you mean to use with `unplugin-vue-components`, it works by static replacement. Which your runtime approach would not work.
