### ISSUE TITLE
How to ignore this warning in PHPStorm? `Unknown html tag`

### ISSUE THREAD

**Issue by anburocky3** [antfu/unplugin-icons#254]
![image](https://user-images.githubusercontent.com/15264938/205247561-6c2a0490-8189-40ac-bb40-71afc9ea0267.png)

**Comment by Emilien-Lambert** [comment]
You can activate the dts option to generate a components.d.ts file, this will allow your ide to solve this warning

Like this:
https://github.com/antfu/unplugin-vue-components#typescript
