### ISSUE TITLE
Unable to use <Component :is=""

### ISSUE THREAD

**Issue by dev-vinicius-andrade** [antfu/unplugin-icons#260]
### Describe the bug

I'm currently using the plugin  and now I need to create some components dynamically.

In my vite.config.ts I've the following configuration 
```typescript 
import ViteIconsResolver from 'unplugin-icons/resolver';
//....
			resolvers: [
				ViteIconsResolver({
					componentPrefix: 'iconify',
					enabledCollections: ['fluent-emoji', 'fluent-emoji-flat', 'fa', 'mdi', 'line-md', 'flagpack', 'ic'],
				}),
			],
```

This allows me to use the component like
```html
<template>
    <IconifyFaFacebookF :color="socialIconsColors" />
</template>
```

But currently i need to make it work more dynamicaly, like: 

```html
 <template>
    <Component v-for="(iconName,index) in availableIcons :color="socialIconsColors" />
</template>
<script setup lang="ts">
import {computed} from 'vue'
const availableIcons = computed(()=>['IconifyFaFacebookF','IconifyFaInstagram']);
</script>
```

But I can't get it to work. Is it possible?

Other thing is that i can't change the icons properties using :width and :height 

### Reproduction

Dynamicaly create icons based on a list of iconNames

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 14.32 GB / 31.91 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.76), ChromiumDev (Hey friend

In an effort to grow oh-my-posh, the decision was made to no
longer support the PowerShell module. Over the past year, the
added benefit of the module disappeared, while the burden of
maintaining it increased.

However, this doesn't mean oh-my-posh disappears from your
terminal, it just means that you'll have to use a different
tool to install it.

All you need to do, is follow the migration guide here:

https://ohmyposh.dev/docs/migrating)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dev-vinicius-andrade** [comment]
any news regarding it?

**Comment by huluobotx** [comment]
I have got the same problem

> <el-sub-menu v-if="showMenuType === 2" :index="pathResolve">
      <template #title>
        <el-icon v-if="menu.meta.icon"><component :is="menu.meta.icon"/></el-icon>
        <span>{{ menu.meta.title }}</span>
      </template>
      <menu-item v-for="(item, key) in menu.children" :key="key" :menu="item" :basePath="pathResolve" />
    </el-sub-menu>
It's not effect

**Comment by dev-vinicius-andrade** [comment]
would be very nice having this feature

**Comment by coderwyd** [comment]
I am now experiencing the same problem, and hope to add that feature in the follow-up.

**Comment by Yiddishe-Kop** [comment]
Currently that auto-imports doesn't work with dynamic components, my workaround was to explicitly import used icons:

```
<template>
    <Component :is="component" />
</template>

<script setup>
import IconTablerHome from '~icons/tabler/smart-home'
import IconTablerListDetails from '~icons/tabler/list-details'
import IconTablerGift from '~icons/tabler/gift'

const props = defineProps({
    name: String,
    set: {
        type: String,
        default: 'tabler',
    },
})

const icons = {
    'tabler-home': IconTablerHome,
    'tabler-list-details': IconTablerListDetails,
    'tabler-gift': IconTablerGift,
}

const component = computed(() => icons[`${props.set}-${props.name}`])
</script>
```

**Comment by antfu** [comment]
https://github.com/antfu/unplugin-icons/issues/5#issuecomment-1005887483

Please search for existing issues before creating one.
