### ISSUE TITLE
Icon* is not defined. eslint react/jsx-no-undef

### ISSUE THREAD

**Issue by adamboof** [antfu/unplugin-icons#271]
### Describe the bug

When use the auto import module for webpack and React, I can get the icons to load fine but I am left with an eslint error for `react/jsx-no-undef`.

I don't particularly want to disable this rule but I can't find any other workaround.

Any help?

### Reproduction

Use the auto-import module with webpack, eslint, React and Typescript

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 89.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 108.0.2
    Safari: 16.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
https://github.com/antfu/unplugin-auto-import#eslint
