### ISSUE TITLE
Add tsconfig instructions to docs

### ISSUE THREAD

**Issue by khari998** [antfu/unplugin-icons#280]
### Clear and concise description of the problem

In order to get my IDE to stop yelling at me over not being able to find the types for the icons, I had to add the types to my tsconfig like so :

```
"compilerOptions": {
		...,
		"types": ["unplugin-icons/types/svelte"]
	}
```

There are different settings for each framework. This should be outlined in the docs as a necessary step for those who use typescript

### Suggested solution

Add tsconfig step in docs for framework specific compilers to avoid compilation errors. Without this, I could not use the `~icons/` syntax for importing icons without the compiler yelling at me 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by khari998** [comment]
Edit: 

There was separate step in the docs that I missed for SvelteKit:

```
For SvelteKit, in the src/app.d.ts file:

/// <reference types="@sveltejs/kit" />
/// <reference types="unplugin-icons/types/svelte" />
```

This also fixes the problem and the tsconfig does not need to be modified

**Comment by SaintPepsi** [comment]
Thanks for posting this. I didn't even think to look at the app.d.ts which has the example: [app.d.ts](https://github.com/unplugin/unplugin-icons/blob/main/examples/sveltekit/src/app.d.ts)

You can add `import 'unplugin-icons/types/svelte'` in your `/src/app.d.ts`
