### ISSUE TITLE
Turbopack support

### ISSUE THREAD

**Issue by AaronNBrock** [antfu/unplugin-icons#281]
### Clear and concise description of the problem

With next js [13 bringing mainstream support for turbopack ](https://nextjs.org/docs/advanced-features/turbopack) in the coming future, I would love to see it turbopack from my favorite icon library!

### Suggested solution

I'm not entirely sure how support for turbopack would be added, I'm happy to help if I can though.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Forwarded to https://github.com/unjs/unplugin/issues/302
