### ISSUE TITLE
Next.js - You may need an additional loader 

### ISSUE THREAD

**Issue by FabienMotte** [antfu/unplugin-icons#46]
Hi there! 👋 
Thanks for the awesome work 👏 

I'm trying to make it work with Next.js (Webpack) but I've an issue:
```You may need an additional loader to handle the result of these loaders.```
Do I need a Webpack loader to make it work?

Reproduction repo: https://github.com/FabienMotte/unplugin-icons-nextjs-issue

![image](https://user-images.githubusercontent.com/662153/132945755-dfbcaccd-8cbc-44ab-b3b3-1631de31eb66.png)

Thank you!

**Comment by antfu** [comment]
Can you share more context here?

**Comment by FabienMotte** [comment]
> Can you share more context here?

Sorry, I accidentally pressed my "Enter" key, you're too fast! Haha

**Comment by FabienMotte** [comment]
Seems like adding the `.jsx` extension to the end of the imported icon works, Webpack knows which loader to use for this file:
```import IconAccountBox from '~icons/mdi/account-box.jsx'```

**Comment by antfu** [comment]
With v0.8.0 now you can set the extension by:

```ts
IconResolver({
  prefix: 'Icons',
  extension: 'jsx'
})
```

**Comment by FabienMotte** [comment]
So cool! Thanks a lot for your time @antfu 🎉 🙏
