### ISSUE TITLE
Default class isn't merged

### ISSUE THREAD

**Issue by Akryum** [antfu/unplugin-icons#53]
Using Vue 2 compiler, setting a `class` on the icon component overrides the default class:

```js
/** @type {import('unplugin-icons').Options} */
const unpluginIconsOptions = {
  compiler: 'vue2',
  defaultClass: 'base-icon svg-wrap',
}
```

```vue
<template>
  <IconCustomSend class="no-info"/>
</template>
```

Result:

```html
<svg data-v-ad45f71a="" class="no-info">...</svg>
```

**Comment by antfu** [comment]
Guess we should introduce a real parser then 😄

**Comment by Akryum** [comment]
Not sure it's related to parsing

**Comment by Akryum** [comment]
https://jsfiddle.net/Akryum/827j9xnu/

**Comment by Akryum** [comment]
Notice the `staticClass` render option

**Comment by Akryum** [comment]
I think it's because of the `v-pre` directive

**Comment by Akryum** [comment]
I don't see a lot of difference with and without:

https://template-explorer.vuejs.org/#%3Csvg%20viewBox%3D%220%200%2024%2024%22%20class%3D%22base-icon%22%3E%0A%09%3Cpath%20d%3D%22M21.48%2011C20.7851%2010.621%203.47885%200.806646%203.47885%200.806646C2.81248%200.443169%202%200.925483%202%201.68454V8.65973C2%209.69991%202.79733%2010.5664%203.83391%2010.6528L13.5017%2011.4585C13.7834%2011.4819%2014%2011.7174%2014%2012V12C14%2012.2826%2013.7834%2012.5181%2013.5017%2012.5415L3.83391%2013.3472C2.79732%2013.4336%202%2014.3001%202%2015.3403V22.3155C2%2023.0745%202.81248%2023.5568%203.47885%2023.1934C3.47885%2023.1934%2020.7851%2013.379%2021.48%2013C22.1749%2012.621%2022.1749%2011.379%2021.48%2011Z%22%2F%3E%0A%3C%2Fsvg%3E%0A

https://template-explorer.vuejs.org/#%3Csvg%20v-pre%20viewBox%3D%220%200%2024%2024%22%20class%3D%22base-icon%22%3E%0A%09%3Cpath%20d%3D%22M21.48%2011C20.7851%2010.621%203.47885%200.806646%203.47885%200.806646C2.81248%200.443169%202%200.925483%202%201.68454V8.65973C2%209.69991%202.79733%2010.5664%203.83391%2010.6528L13.5017%2011.4585C13.7834%2011.4819%2014%2011.7174%2014%2012V12C14%2012.2826%2013.7834%2012.5181%2013.5017%2012.5415L3.83391%2013.3472C2.79732%2013.4336%202%2014.3001%202%2015.3403V22.3155C2%2023.0745%202.81248%2023.5568%203.47885%2023.1934C3.47885%2023.1934%2020.7851%2013.379%2021.48%2013C22.1749%2012.621%2022.1749%2011.379%2021.48%2011Z%22%2F%3E%0A%3C%2Fsvg%3E%0A

**Comment by Akryum** [comment]
Maybe this commit should probably reverted? https://github.com/antfu/unplugin-icons/commit/62866166a3c07a7612b584cd7c52e9f0bf26b91e

**Comment by Akryum** [comment]
I confirm commenting the line that adds `v-pre` fixes the issue:

![image](https://user-images.githubusercontent.com/2798204/133413845-f6d1938b-31d8-4cf2-babb-bedc7e652f40.png)
