### ISSUE TITLE
Vite + React build fails

### ISSUE THREAD

**Issue by oferitz** [antfu/unplugin-icons#64]
<img width="1017" alt="Screen Shot 2021-09-16 at 10 56 45" src="https://user-images.githubusercontent.com/1668687/133573777-0b16043b-136b-4d52-9b29-f77dd05c534a.png">
<img width="649" alt="Screen Shot 2021-09-16 at 10 57 15" src="https://user-images.githubusercontent.com/1668687/133573782-8d27a6e3-6de4-46f4-ba8e-a7c329b3d064.png">

**vite.config.ts**
```ts
import { defineConfig } from 'vite'
import reactRefresh from '@vitejs/plugin-react-refresh'
import tsconfigPaths from 'vite-tsconfig-paths'
import Icons from 'unplugin-icons/vite'
import { visualizer } from 'rollup-plugin-visualizer'

export default defineConfig({
  plugins: [
    reactRefresh(),
    tsconfigPaths(),
    Icons({ compiler: 'jsx', jsx: 'react' }),
    visualizer()
  ]
})
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "types": ["unplugin-icons/types/react"]
  },
  "include": ["./src"]
}
```

**Comment by userquin** [comment]
@oferitz can you test it adding it to `src/vite-env.d.ts` file?:
```html
/// <reference types="vite/client" />
/// <reference types="unplugin-icons/types/svelte" />
```
If previous works, PR welcome...

**Comment by userquin** [comment]
on IntelliJ adding the type there works:

![imagen](https://user-images.githubusercontent.com/6311119/133623338-ebb033fd-bb4d-4292-9164-03b5360c37bd.png)

![imagen](https://user-images.githubusercontent.com/6311119/133623134-c290c433-ccc2-4505-9976-93569e0335cd.png)

**Comment by oferitz** [comment]
@userquin added ```/// <reference types="unplugin-icons/types/react" />``` to `src/vite-env.d.ts` unfortunately it still fails on build time. In dev mode it's working fine (even without the above line).

**Comment by userquin** [comment]
@oferitz so there are 2 problems, former for dev (solved), but now the build fails? Can you provide some system info via `npx envinfo --system --npmPackages vite,@vitejs/plugin-vue --binaries --browsers`?

On local it works:

```shell
F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\examples\vite-react>pnpm run build

> vite-react@0.0.0 build F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\examples\vite-react
> vite build

vite v2.5.7 building for production...
✓ 27 modules transformed.
dist/index.html                  0.45 KiB
dist/assets/index.d93758c6.css   0.77 KiB / brotli: 0.41 KiB
dist/assets/index.698ae786.js    5.93 KiB / brotli: 2.54 KiB
dist/assets/vendor.69887640.js   127.61 KiB / brotli: 36.05 KiB
```

**Comment by userquin** [comment]
Sorry on the info I added vue plugin instead react...

**Comment by oferitz** [comment]
@userquin Just to be clear there was never a problem in dev mode. my original issue was regrading build time.
here is the info you asked:
```
 npx envinfo --system --npmPackages vite,@vitejs/plugin-vue --binaries --browsers
npx: installed 1 in 1.471s

  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Apple M1
    Memory: 265.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Firefox Developer Edition: 93.0
    Safari: 14.1
  npmPackages:
    vite: ^2.5.4 => 2.5.6 
```
also in your example above you are building with `pnpm` and i'm using `yarn`. don't know if it matters.

**Comment by userquin** [comment]
Then it is not a problem with the build it is a problem on your repo layout, you should upgrage to add lerna and link vite-react project to use lerna, see the `package.json` file.

Maybe to do a test remove `"unplugin-icons": "workspace:*",` entry from the vite-react package.json file, then `yarn add unplugin-icons -D` then `yarn build`.

**Comment by oferitz** [comment]
@userquin Not sure i'm following. In my project `package.json` there isn't any `"unplugin-icons": "workspace:*"` entry.
also why do I need to add `lerna` in order to use `unplugin-icons` in my project?

**Comment by userquin** [comment]
so the exmaple is not working on your project, not in a clone: take a look at this entry: just add `jsx: 'react'` to the plugin (https://github.com/antfu/unplugin-icons/pull/67/files)

**Comment by oferitz** [comment]
@userquin It's already defined like that :) take a look at my first post above, I wrote all the details of how my project is defined

**Comment by userquin** [comment]
with the fix on the PR I have it working (without it the react example fails with your error):

![imagen](https://user-images.githubusercontent.com/6311119/133630491-bfc2d381-2d22-4f2e-9833-7a80f8756190.png)

**Comment by oferitz** [comment]
@userquin yeah it's working on dev mode for me also. but did you try to build it? with `tsc && vite build`

**Comment by userquin** [comment]
@oferitz we don't use `tsc`, my `build` output:
```shell
F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\examples\vite-react>pnpm run build

> vite-react@0.0.0 build F:\work\projects\quini\GitHub\antfu\unplugin-projects\unplugin-icons\examples\vite-react
> vite build

vite v2.5.7 building for production...
✓ 27 modules transformed.
dist/index.html                  0.45 KiB
dist/assets/index.d93758c6.css   0.77 KiB / brotli: 0.41 KiB
dist/assets/index.f20f6b9a.js    5.94 KiB / brotli: 2.54 KiB
dist/assets/vendor.69887640.js   127.61 KiB / brotli: 36.05 KiB
```

**Comment by userquin** [comment]
just see `examples/vite-react/package.json` on this repo

**Comment by oferitz** [comment]
@userquin Thanks, finally we understand each other :) so just that you know running with `tsc` will fail and that's what my issue is all about, Maybe it worth taking a look on why. 
Thank you so much for the quick response and the time you took trying to help 🙏

**Comment by userquin** [comment]
@oferitz if you're using vite just try `vite build`, should work.
