### ISSUE TITLE
incorrect typing for svelte elements

### ISSUE THREAD

**Issue by kafai97** [antfu/unplugin-icons#73]
## Problem Description
Following the installation guide for sveltekit, it works fine on runtime but vscode typescript checking will keep raising error `JSX element type does not have any construct or call signatures`. 

Screenshot attached as below.
<img width="1200" alt="Screenshot 2021-09-28 at 10 37 31 PM" src="https://user-images.githubusercontent.com/41912520/135109030-ad549f91-f0cf-4503-bd04-6528074b2032.png">
 
## Possible Solution
According to svelte, [a svelte component should have the following typing](https://github.com/sveltejs/svelte/blob/e45d1801621c587a08cb3f0961a9109c22e074ba/src/runtime/ambient.ts#L1-L3)
```ts
declare module '*.svelte' {
	export { SvelteComponentDev as default } from 'svelte/internal';
}
```

And it does work after applying those change.
If you guys think it makes sense, I will create a PR on it.

**Comment by userquin** [comment]
can you take a look at this https://github.com/antfu/unplugin-icons/blob/main/types/svelte.d.ts?

so your suggestion is adding `.svelte` suffix to both modules?

**Comment by userquin** [comment]
uhmm looks good, PR welcome (on `intellij/webstorm` changes looks better /cc @bluwy /cc @dominikg):

![imagen](https://user-images.githubusercontent.com/6311119/135125404-48b5934d-c5c5-4c9c-bbb9-66364190443a.png)

while with current version:

![imagen](https://user-images.githubusercontent.com/6311119/135125459-c1848caf-134e-4055-83eb-3e1262aeea33.png)

**Comment by bluwy** [comment]
@kafai97's suggestion looks good. Matches [svelte's](https://github.com/sveltejs/svelte/blob/dafbdc286eef3de2243088a9a826e6899e20465c/src/runtime/ambient.ts) as well. I'm wondering it if's one of those `typeof SvelteComponentDev` trick, but still, following Svelte's official ambient types would be more robust.
