### ISSUE TITLE
importing icons works but vs-code doesn't recognize import path

### ISSUE THREAD

**Issue by ksnyde** [antfu/unplugin-icons#77]
I am using _auto_-importing icons in VueJS templates without issue and in fact I can also import icons explicitly in TS like so:

```ts
import Done from "~icons/mdi/checkbox-marked-outline";
import NotStarted from "~icons/mdi/checkbox-blank-outline";
import InProgress from "~icons/mdi/checkbox-indeterminate";
import Blocked from "~icons/mdi:alert-box-outline";

export const statusIcon = {
  done: Done,
  notStarted: NotStarted,
  inProgress: InProgress,
  blocked: Blocked,
};
```

And while this code works, the `~icons` prefix seems to not be understood by **vs-code** and I get an ugly rash of curly underlines:

![image](https://user-images.githubusercontent.com/980757/135727858-f3a06b02-7b7a-41d5-8f54-c821120be3bb.png)

**Comment by userquin** [comment]
@ksnyde see https://github.com/antfu/unplugin-icons#frameworks

**Comment by ksnyde** [comment]
Oh shoot; you're right I missed that. Now I do indeed avoid the _red squiggles_ but now I get a run-time error:

![image](https://user-images.githubusercontent.com/980757/135730167-065439ab-fe00-44d2-bceb-2765d8a5989b.png)

**Comment by ksnyde** [comment]
Note: this is just a mildly modified template of the **vitesse** starter kit

**Comment by ksnyde** [comment]
Is there any additional configuration if you're doing the imports in a `.ts` file instead of a `.vue` file?
