### ISSUE TITLE
cyan not found in chalk, Vite-Svelte and pnpm

### ISSUE THREAD

**Issue by PuruVJ** [antfu/unplugin-icons#80]
Hi, so I added unplugin to a repo, and it broke everything for some reason. The error is this

![image](https://user-images.githubusercontent.com/47742487/135905807-0c17912e-3ed8-4864-b335-c73656144770.png)

I installed chalk to mitigate this issue, but it wouldn't go away, and hence, I can't turn on the dev server

Here's the repo https://github.com/PuruVJ/ms-todo-svelte

Thanks
Puru

**Comment by userquin** [comment]
`chalk` doesn't provide  `esm`, so we need to change its usage.

**Comment by PuruVJ** [comment]
Or maybe this? Seems compatible with chalk https://www.npmjs.com/package/nanocolors

**Comment by userquin** [comment]
uhmm, maybe it will better to change the dependency, good catch man

**Comment by PuruVJ** [comment]
Yeah, would also save us some kbs, and seems imple considering it's used only once in the codebase

**Comment by userquin** [comment]
updated

**Comment by PuruVJ** [comment]
Superb!!

**Comment by userquin** [comment]
@PuruVJ 

With `autoInstall` works with your fork with `0.12.9`. We're changing to use `picocolors` instead `nanocolors`, it seems it will be closed in favor of `picocolors` (no esm support yet).

I'm checking on local with `picocolors` on your repo.

![imagen](https://user-images.githubusercontent.com/6311119/136069498-47b09f4d-3268-4c07-b56a-6912e2dddb38.png)

**Comment by PuruVJ** [comment]
Wait, so yur saying autoInstall is not working due to nanocolors? 🤯

**Comment by userquin** [comment]
No, `autoInstall`  works like a charm man, I'll change to use `picococlores` since `nanocolors` has been deleted/deprecated, see PR #83 comments

**Comment by userquin** [comment]
The  `autoInstall` is an experimental thing to allow use the icons without the package installed, then `unplugin-icons` will install for you on dev, see the logs on console.

The `[listID].svelte` file looks like this:

![imagen](https://user-images.githubusercontent.com/6311119/136079118-e9054fa5-06ed-4659-88cb-91461ae08b62.png)

**Comment by userquin** [comment]
Upps, the PR has no comments, you can see on the `nanocolors` repo or in #82 issue

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/136079663-d098495b-26a4-4dc0-989d-0e3f5ff1e9c4.png)

**Comment by PuruVJ** [comment]
We've already bikeshedded this quite a bit, but would you consider using kolorist for this task @antfu ?

It's small, deps free, fully ESM, and most importantly, by the preact guy @marvinhagemeister, so it's reliable as an army tank.

Here's all the code it has https://github.com/marvinhagemeister/kolorist/blob/main/src/index.ts

Would love to make a PR
