### ISSUE TITLE
Add support for @iconify/json icon sets in customCollections

### ISSUE THREAD

**Issue by jceb** [antfu/unplugin-icons#87]
As mentioned [here](https://github.com/antfu/unplugin-icons/issues/12#issuecomment-938395379), @iconfiy/json style icon sets are currently not supported by the `customCollections` attribute of unplugin-icons. Support for this feature would be very helpful to integrate commercial icons like Font Awesome Pro.

As an alternative to supporting json style icon sets a the loader function could be extended to apply the `fill="currentColor"` attribute and other useful defaults (see `@iconify/utils/lib/customisations`) to SVG files. This way commercial icons like Font Awesome Pro could be loaded directly.

Personally, I lean towards the alternative because it removes the JSON build step that's required for the first approach. Having said that, I'm not familiar with the implications of not going with the JSON approach.

**Comment by antfu** [comment]
I am not sure if what `./json/fab.json` in your code snippet really is. But if it's compatible with Iconify's json data, I think we could export the icon resolver and maybe add an `IconifyLoader` to be reused for custom sources.

Meanwhile, I see your use FileSystemLoader in your first approach, https://github.com/antfu/unplugin-icons/issues/12#issuecomment-937631130, if that's preferable, we could have a custom transform function to `FileSystemLoader` as mentioned in #52.

So the usage could be like 

```js
"fap-brands": FileSystemIconLoader(
  "PATH_TO/node_modules/@fortawesome/fontawesome-pro/svgs/brands",
  svg => svg.replace(/^<svg /, '<svg fill="currentColor" ')
),
```
