### ISSUE TITLE
Add support for markojs

### ISSUE THREAD

**Issue by dephiros** [antfu/unplugin-icons#93]
Add support for markojs

I want to use this plugin with markojs but not sure how to contribute. @DylanPiercey or @ryansolid, would one you be able to point to the right direction?

**Comment by userquin** [comment]
@DylanPiercey I add your code and also add `.marko` extension to resolve marko component: https://markojs.com/docs/class-components/#single-file-components

@dephiros can you test using it using this branch? https://github.com/antfu/unplugin-icons/tree/feat/add-marko-compiler

**Comment by userquin** [comment]
@DylanPiercey I think the plugin should return `.js` as extension, then on the compiler template render the code you provide to escape the svg html tag. 
It seems if adding `.marko` extension, marko vite plugin will try to resolve the component from the component directory and so it fails.

I only test it using vite. I have found multiple errors using  marko vite example on Windows with node 15.
