### ISSUE TITLE
svgr is not a function

### ISSUE THREAD

**Issue by IanVS** [antfu/unplugin-icons#96]
Thanks very much for fixing #65.

I'm now seeing `svgr is not a function`, and find that I need to change the compiled code from:

```
const svgr = (await importModule("@svgr/core")).default;
```

to 

```
const svgr = (await importModule("@svgr/core")).default.default;
```

and then my app and tests work as expected.

**Comment by Xwudao** [comment]
@antfu maybe need change it back?

when install `"@svgr/core": "^6.1.0",` it also occur error: `svgr is not a function`

But, when I reinstall `"@svgr/core": "^5.1.0",`, it's ok!

**Comment by IanVS** [comment]
@Xwudao it's probably best if you could open a new issue with some details about what you're seeing.  I think this is due to a change in svgr, which now uses named exports instead of a default export.

**Comment by Xwudao** [comment]
> 

yeah! That's what I mean.

I install latest version both of  `unplugin-icons`  and `@svgr/core(6.1.0)`, an error occurred.

I found this issue, and I try to install "@svgr/core": "^5.1.0", it's working.

**Comment by userquin** [comment]
@Xwudao @IanVS @antfu it seems the `default` export on `v5` becomes `transform` on `v6`, I'm fixing it, PR in a few minutes...
